added Provider data type, query, resolver
MetaTech-dev/health-quiz-server pull request #15
Opened 2021-01-04 18:50 UTC by mareklubomirski

2021-01-04 18:54 UTC, matthewjwhitney requested changes

2021-01-04 18:54 UTC, matthewjwhitney commented on src/index.js
> +    id: ID
i updated the issue like 20 minutes ago so you didn't see it obviously but this field should be required. that was my mistake when creating the issue. so it should be
`id: ID!`

2021-01-04 18:54 UTC, matthewjwhitney commented on src/index.js
> +    provider: () => Provider,
the resolver should return the test data, not the type. so it should be
`provider: () => provider,`

2021-01-04 18:57 UTC, matthewjwhitney requested changes

2021-01-04 18:57 UTC, matthewjwhitney commented on src/index.js
> +    provider: [Provider]
this should be plural because we're returning more than one provider. so it should be:
`providers: [Provider]`

2021-01-04 18:57 UTC, matthewjwhitney commented on src/index.js
> +    provider: () => Provider,
this should be plural.
this should return the data not the type.
so it should be:
`providers: () => providers,`

2021-01-04 19:56 UTC, matthewjwhitney approved these changes

2021-01-05 00:08 UTC, austenm approved these changes

2021-01-05 01:34 UTC, merged