feat(Person): create, update, and delete mutations
MetaTech-dev/health-quiz-server pull request #24
Opened 2021-01-13 04:20 UTC by MetaMatt1

closes #16

2021-01-14 23:01 UTC, austenm approved these changes

2021-01-16 03:07 UTC, RhyecaRiley approved these changes

2021-01-16 03:18 UTC, RhyecaRiley approved these changes

2021-01-16 04:22 UTC, RhyecaRiley requested changes

2021-01-16 04:22 UTC, RhyecaRiley commented on src/Person/resolvers.js
> +      console.log(personsData);
Remove me

2021-01-16 04:22 UTC, RhyecaRiley commented on src/Person/resolvers.js
> +      console.log(personsData);
Remove me

2021-01-16 05:25 UTC, austenm requested changes
Get rid of them console logs

2021-01-16 21:56 UTC, mareklubomirski approved these changes

2021-01-16 23:02 UTC, RhyecaRiley approved these changes

2021-01-16 23:10 UTC, merged