feat(Provider): create, update, and delete mutations
MetaTech-dev/health-quiz-server pull request #30
Opened 2021-01-16 21:53 UTC by mareklubomirski

closes #18

2021-01-16 22:01 UTC, MetaMatt1 requested changes
let me know if you want to meet to go over the feedback. this is a good start but needs some more work.

2021-01-16 22:01 UTC, MetaMatt1 commented on src/Provider/resolvers.js
> +        providersData[providerIndex].id = id;
we're using the id  for looking up the provider. you did that correctly on line 26. we don't want to change the id though like you're doing here. we want to update the name or url if those are passed as arguments.

2021-01-16 22:14 UTC, MetaMatt1 commented
nice quick work on that fix. looks good. did you test your work in the playground?

2021-01-16 23:08 UTC, MetaMatt1 approved these changes

2021-01-16 23:21 UTC, MetaMatt1 approved these changes

2021-01-17 21:09 UTC, RhyecaRiley approved these changes

2021-01-17 21:37 UTC, merged